package web.salons.model;
// Generated Feb 22, 2021 12:43:00 AM by Hibernate Tools 4.3.1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Appointments generated by hbm2java
 */
@Entity
@Table(name = "appointments", schema = "dbo", catalog = "SalonNails")
public class Appointment implements java.io.Serializable {

	private int appointmentId;
	private Client clients;
	private Employee employees;
	private Salon salons;
	private Date timeBooked;
	private Boolean canceled;
	private Date dateBooked;
	private String phone;
	private String listServices;
	private Services services;

	public Appointment() {
		
	}
	
	public Appointment(Salon salons, Date timeBooked, Boolean canceled,
			Date dateBooked, String phone, String listServices) {
		super();
		this.salons = salons;
		this.timeBooked = timeBooked;
		this.canceled = canceled;
		this.dateBooked = dateBooked;
		this.phone = phone;
		this.listServices = listServices;
	}

	public Appointment(Employee employees, Salon salons, Date timeBooked, Boolean canceled,
			Date dateBooked, String phone, String listServices) {
		super();
		this.employees = employees;
		this.salons = salons;
		this.timeBooked = timeBooked;
		this.canceled = canceled;
		this.dateBooked = dateBooked;
		this.phone = phone;
		this.listServices = listServices;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "appointmentID", unique = true, nullable = false)
	public int getAppointmentId() {
		return this.appointmentId;
	}

	public void setAppointmentId(int appointmentId) {
		this.appointmentId = appointmentId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "userEmail", nullable = true)
	public Client getClients() {
		return this.clients;
	}

	public void setClients(Client clients) {
		this.clients = clients;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "employeeID", nullable = true)
	public Employee getEmployees() {
		return this.employees;
	}

	public void setEmployees(Employee employees) {
		this.employees = employees;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "salonID", nullable = false)
	public Salon getSalons() {
		return this.salons;
	}

	public void setSalons(Salon salons) {
		this.salons = salons;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "serviceID", nullable = true)
	public Services getServices() {
		return services;
	}

	public void setServices(Services services) {
		this.services = services;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "timeBooked", nullable = false, length = 23)
	public Date getTimeBooked() {
		return this.timeBooked;
	}

	public void setTimeBooked(Date timeBooked) {
		this.timeBooked = timeBooked;
	}

	@Column(name = "canceled")
	public Boolean getCanceled() {
		return this.canceled;
	}

	public void setCanceled(Boolean canceled) {
		this.canceled = canceled;
	}
	

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dateBooked", nullable = false, length = 23)
	public Date getDateBooked() {
		return this.dateBooked;
	}

	public void setDateBooked(Date dateBooked) {
		this.dateBooked = dateBooked;
	}

	@Column(name = "phone", nullable = false, length = 50)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}
	
	@Column(name = "listServices", nullable = true, length = 1000)
	public String getListServices() {
		return listServices;
	}

	public void setListServices(String listServices) {
		this.listServices = listServices;
	}
	
	

}
