package web.salons.model;
// Generated Feb 22, 2021 12:43:00 AM by Hibernate Tools 4.3.1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Appointments generated by hbm2java
 */
@Entity
@Table(name = "appointments", schema = "dbo", catalog = "SalonNails")
public class Appointment implements java.io.Serializable {
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "appointmentID", unique = true)
	private int appointmentId;
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "timeBooked")
	private Date timeBooked;
	@Column(name = "canceled")
	private Boolean canceled;
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dateBooked")
	private Date dateBooked;
	@Column(name = "phone")
	private String phone;
	@Column(name = "listServices")
	private String listServices;
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "userID")
	private Client clients;
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "employeeID")
	private Employee employees;
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "salonID")
	private Salon salons;
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "serviceID")
	private Services services;

	public Appointment() {

	}

	public Appointment(Salon salons, Date timeBooked, Boolean canceled, Date dateBooked, String phone,
			String listServices) {
		super();
		this.salons = salons;
		this.timeBooked = timeBooked;
		this.canceled = canceled;
		this.dateBooked = dateBooked;
		this.phone = phone;
		this.listServices = listServices;
	}

	public Appointment(Client clients, Employee employees, Salon salons, Date timeBooked, Boolean canceled,
			Date dateBooked, String phone, String listServices) {
		super();
		this.clients = clients;
		this.employees = employees;
		this.salons = salons;
		this.timeBooked = timeBooked;
		this.canceled = canceled;
		this.dateBooked = dateBooked;
		this.phone = phone;
		this.listServices = listServices;
	}

	public Appointment(Employee employees, Salon salons, Date timeBooked, Boolean canceled, Date dateBooked,
			String phone, String listServices) {
		super();
		this.employees = employees;
		this.salons = salons;
		this.timeBooked = timeBooked;
		this.canceled = canceled;
		this.dateBooked = dateBooked;
		this.phone = phone;
		this.listServices = listServices;
	}

	public int getAppointmentId() {
		return this.appointmentId;
	}

	public void setAppointmentId(int appointmentId) {
		this.appointmentId = appointmentId;
	}

	public Client getClients() {
		return this.clients;
	}

	public void setClients(Client clients) {
		this.clients = clients;
	}

	public Employee getEmployees() {
		return this.employees;
	}

	public void setEmployees(Employee employees) {
		this.employees = employees;
	}

	public Salon getSalons() {
		return this.salons;
	}

	public void setSalons(Salon salons) {
		this.salons = salons;
	}

	public Services getServices() {
		return services;
	}

	public void setServices(Services services) {
		this.services = services;
	}

	public Date getTimeBooked() {
		return this.timeBooked;
	}

	public void setTimeBooked(Date timeBooked) {
		this.timeBooked = timeBooked;
	}

	public Boolean getCanceled() {
		return this.canceled;
	}

	public void setCanceled(Boolean canceled) {
		this.canceled = canceled;
	}

	public Date getDateBooked() {
		return this.dateBooked;
	}

	public void setDateBooked(Date dateBooked) {
		this.dateBooked = dateBooked;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getListServices() {
		return listServices;
	}

	public void setListServices(String listServices) {
		this.listServices = listServices;
	}

}
