package web.salons.model;
// Generated Feb 22, 2021 12:43:00 AM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Employees generated by hbm2java
 */
@Entity
@Table(name = "employees", schema = "dbo", catalog = "SalonNails")
public class Employee implements java.io.Serializable {
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "employeeID", unique = true, nullable = false)
	private int employeeId;
	@Column(name = "fullName", nullable = false)
	private String fullName;
	@Column(name = "timeOfEmp", nullable = false, length = 1000)
	private String timeOfEmp;
	@Temporal(TemporalType.TIME)
	@Column(name = "timeStart", nullable = false, length = 16)
	private Date timeStart;
	@Temporal(TemporalType.TIME)
	@Column(name = "timeEnd", nullable = false, length = 16)
	private Date timeEnd;
	@Column(name = "shift", nullable = false, length = 30)
	private String shift;
	@JsonIgnore
	@ManyToMany(fetch = FetchType.LAZY, cascade = CascadeType.MERGE)
	@JoinTable(name = "salons_employees",
		joinColumns = { @JoinColumn(name = "employeeID")},
		inverseJoinColumns = { @JoinColumn (name = "salonID")})
	private Set<Salon> salons = new HashSet<>();
	@JsonIgnore
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "employees")
	private Set<Appointment> appointmentses = new HashSet<Appointment>(0);

	public Employee() {
		
	}



	public Employee( String fullName, String timeOfEmp, Date timeStart, Date timeEnd,
			String shift) {
		
		this.fullName = fullName;
		this.timeOfEmp = timeOfEmp;
		this.timeStart = timeStart;
		this.timeEnd = timeEnd;
		this.shift = shift;
	}


	public int getEmployeeId() {
		return this.employeeId;
	}

	public void setEmployeeId(int employeeId) {
		this.employeeId = employeeId;
	}

	
	public String getFullName() {
		return this.fullName;
	}

	public void setFullName(String fullName) {
		this.fullName = fullName;
	}

	
	public String getTimeOfEmp() {
		return this.timeOfEmp;
	}

	public void setTimeOfEmp(String timeOfEmp) {
		this.timeOfEmp = timeOfEmp;
	}

	
	public Date getTimeStart() {
		return this.timeStart;
	}

	public void setTimeStart(Date timeStart) {
		this.timeStart = timeStart;
	}

	
	public Date getTimeEnd() {
		return this.timeEnd;
	}

	public void setTimeEnd(Date timeEnd) {
		this.timeEnd = timeEnd;
	}

	
	public String getShift() {
		return this.shift;
	}

	public void setShift(String shift) {
		this.shift = shift;
	}

//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "employees")
//	public Set<SalonEmployee> getSalonsEmployeeses() {
//		return this.salonsEmployeeses;
//	}
//
//	public void setSalonsEmployeeses(Set<SalonEmployee> salonsEmployeeses) {
//		this.salonsEmployeeses = salonsEmployeeses;
//	}
	
	public Set<Appointment> getAppointmentses() {
		return this.appointmentses;
	}

	public Set<Salon> getSalons() {
		return salons;
	}

	public void setSalons(Set<Salon> salons) {
		this.salons = salons;
	}

	public void setAppointmentses(Set<Appointment> appointmentses) {
		this.appointmentses = appointmentses;
	}

}
