package web.salons.model;
// Generated Feb 22, 2021 12:43:00 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Roles generated by hbm2java
 */
@Entity
@Table(name = "roles", schema = "dbo", catalog = "SalonNails")
public class Role implements java.io.Serializable  {

	private String roleId;
	private String roleName;
	private Set<UserRole> usersRoleses = new HashSet<UserRole>(0);

	public Role() {
	}

	public Role(String roleId) {
		this.roleId = roleId;
	}

	public Role(String roleId, String roleName, Set<UserRole> usersRoleses) {
		this.roleId = roleId;
		this.roleName = roleName;
		this.usersRoleses = usersRoleses;
	}

	@Id
	@Column(name = "roleID", unique = true, nullable = false, length = 10)
	public String getRoleId() {
		return this.roleId;
	}

	public void setRoleId(String roleId) {
		this.roleId = roleId;
	}

	@Column(name = "roleName", length = 30)
	public String getRoleName() {
		return this.roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "roles")
	public Set<UserRole> getUsersRoleses() {
		return this.usersRoleses;
	}

	public void setUsersRoleses(Set<UserRole> usersRoleses) {
		this.usersRoleses = usersRoleses;
	}

}
