package web.salons.model;
// Generated Feb 22, 2021 12:43:00 AM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Salons generated by hbm2java
 */
@Entity
@Table(name = "salons", schema = "dbo", catalog = "SalonNails")
public class Salon implements java.io.Serializable {
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "salonID", unique = true, nullable = false)
	private int salonId;
	@Column(name = "salonName", nullable = false, length = 50)
	private String salonName;
	@Column(name = "address", nullable = false, length = 50)
	private String address;
	@Temporal(TemporalType.TIME)
	@Column(name = "timeStart", nullable = false, length = 16)
	private Date timeStart;
	@Temporal(TemporalType.TIME)
	@Column(name = "timeEnd", nullable = false, length = 16)
	private Date timeEnd;
	@Column(name = "timeOfSalon", nullable = false, length = 1000)
	private String timeOfSalon;
	@Column(name = "phone", nullable = false, length = 50)
	private String phone;	
	@Column(name = "city", nullable = false, length = 50)
	private String city;
	
	@JsonIgnore
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "salons")
	private Set<Appointment> appointmentses = new HashSet<Appointment>(0);
	@JsonIgnore
	@ManyToMany(fetch = FetchType.LAZY, cascade = CascadeType.ALL, mappedBy = "salons")
	private Set<Employee> employees = new HashSet<>();
	
	public Salon() {
		
	}
	
	public Salon(int salonId) {
		super();
		this.salonId = salonId;
	}



	public Salon(String salonName, String address, String city, Date timeStart, Date timeEnd, String timeOfSalon, String phone) {
		super();
		this.salonName = salonName;
		this.address = address;
		this.city = city;
		this.timeStart = timeStart;
		this.timeEnd = timeEnd;
		this.timeOfSalon = timeOfSalon;
		this.phone = phone;
	}



	
	public int getSalonId() {
		return this.salonId;
	}

	public void setSalonId(int salonId) {
		this.salonId = salonId;
	}

	
	public String getSalonName() {
		return this.salonName;
	}

	public void setSalonName(String salonName) {
		this.salonName = salonName;
	}

	
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	
	public Date getTimeStart() {
		return this.timeStart;
	}

	public void setTimeStart(Date timeStart) {
		this.timeStart = timeStart;
	}

	
	public Date getTimeEnd() {
		return this.timeEnd;
	}

	public void setTimeEnd(Date timeEnd) {
		this.timeEnd = timeEnd;
	}

	
	public String getTimeOfSalon() {
		return this.timeOfSalon;
	}

	public void setTimeOfSalon(String timeOfSalon) {
		this.timeOfSalon = timeOfSalon;
	}

	
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}
	
	
	public String getCity() {
		return city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public Set<Appointment> getAppointmentses() {
		return this.appointmentses;
	}

	public void setAppointmentses(Set<Appointment> appointmentses) {
		this.appointmentses = appointmentses;
	}

	public Set<Employee> getEmployees() {
		return employees;
	}



	public void setEmployees(Set<Employee> employees) {
		this.employees = employees;
	}
	
	
//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "salons")
//	public Set<SalonEmployee> getSalonsEmployeeses() {
//		return this.salonsEmployeeses;
//	}
//
//	public void setSalonsEmployeeses(Set<SalonEmployee> salonsEmployeeses) {
//		this.salonsEmployeeses = salonsEmployeeses;
//	}

}
