package web.salons.model;
// Generated Feb 22, 2021 12:43:00 AM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Salons generated by hbm2java
 */
@Entity
@Table(name = "salons", schema = "dbo", catalog = "SalonNails")
public class Salon implements java.io.Serializable {
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "salonID", unique = true)
	private int salonId;
	@Column(name = "salonName")
	private String salonName;
	@Column(name = "roadAndNumber")
	private String roadAndNumber;
	@Temporal(TemporalType.TIME)
	@Column(name = "timeStart")
	private Date timeStart;
	@Temporal(TemporalType.TIME)
	@Column(name = "timeEnd")
	private Date timeEnd;
	@Column(name = "timeOfSalon")
	private String timeOfSalon;
	@Column(name = "phone")
	private String phone;
	@Column(name = "city")
	private String city;
	@Column(name = "ward")
	private String ward;
	@Column(name = "imageSalon")
	private String imageSalon;
	@JsonIgnore
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "salons")
	private Set<Appointment> appointmentses = new HashSet<Appointment>(0);
	@JsonIgnore
	@ManyToMany(fetch = FetchType.LAZY, cascade = CascadeType.ALL, mappedBy = "salons")
	private Set<Employee> employees = new HashSet<>();

	public Salon() {

	}

	public Salon(int salonId) {
		super();
		this.salonId = salonId;
	}

	public Salon(int salonId, String salonName, String roadAndNumber, Date timeStart, Date timeEnd, String timeOfSalon,
			String phone, String city, String ward, String imageSalon) {
		super();
		this.salonId = salonId;
		this.salonName = salonName;
		this.roadAndNumber = roadAndNumber;
		this.timeStart = timeStart;
		this.timeEnd = timeEnd;
		this.timeOfSalon = timeOfSalon;
		this.phone = phone;
		this.city = city;
		this.ward = ward;
		this.imageSalon = imageSalon;
	}

	public Salon(String salonName, String roadAndNumber, Date timeStart, Date timeEnd, String timeOfSalon, String phone,
			String city, String ward) {
		super();
		this.salonName = salonName;
		this.roadAndNumber = roadAndNumber;
		this.timeStart = timeStart;
		this.timeEnd = timeEnd;
		this.timeOfSalon = timeOfSalon;
		this.phone = phone;
		this.city = city;
		this.ward = ward;
	}

	public Salon(String salonName, String roadAndNumber, Date timeStart, Date timeEnd, String timeOfSalon, String phone,
			String city, String ward, String imageSalon) {
		super();
		this.salonName = salonName;
		this.roadAndNumber = roadAndNumber;
		this.timeStart = timeStart;
		this.timeEnd = timeEnd;
		this.timeOfSalon = timeOfSalon;
		this.phone = phone;
		this.city = city;
		this.ward = ward;
		this.imageSalon = imageSalon;
	}

	public int getSalonId() {
		return this.salonId;
	}

	public void setSalonId(int salonId) {
		this.salonId = salonId;
	}

	public String getSalonName() {
		return this.salonName;
	}

	public void setSalonName(String salonName) {
		this.salonName = salonName;
	}

	public String getRoadAndNumber() {
		return roadAndNumber;
	}

	public void setRoadAndNumber(String roadAndNumber) {
		this.roadAndNumber = roadAndNumber;
	}

	public Date getTimeStart() {
		return this.timeStart;
	}

	public void setTimeStart(Date timeStart) {
		this.timeStart = timeStart;
	}

	public Date getTimeEnd() {
		return this.timeEnd;
	}

	public void setTimeEnd(Date timeEnd) {
		this.timeEnd = timeEnd;
	}

	public String getTimeOfSalon() {
		return this.timeOfSalon;
	}

	public void setTimeOfSalon(String timeOfSalon) {
		this.timeOfSalon = timeOfSalon;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getCity() {
		return city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getWard() {
		return ward;
	}

	public void setWard(String ward) {
		this.ward = ward;
	}

	public String getImageSalon() {
		return imageSalon;
	}

	public void setImageSalon(String imageSalon) {
		this.imageSalon = imageSalon;
	}

	public Set<Appointment> getAppointmentses() {
		return this.appointmentses;
	}

	public void setAppointmentses(Set<Appointment> appointmentses) {
		this.appointmentses = appointmentses;
	}

	public Set<Employee> getEmployees() {
		return employees;
	}

	public void setEmployees(Set<Employee> employees) {
		this.employees = employees;
	}

	@Override
	public String toString() {
		return salonName;
	}

}