package web.salons.model;
// Generated Feb 22, 2021 12:43:00 AM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.ColumnResult;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SqlResultSetMapping;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.NamedNativeQuery;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * ServicesDetaids generated by hbm2java
 */
@Entity
@Table(name = "services_details", schema = "dbo", catalog = "SalonNails")
public class ServiceDetail implements java.io.Serializable {
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "serviceDetailID", unique = true, nullable = false)
	private int serviceDetailId;
	@JsonIgnore
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "serviceID", nullable = false)
	private Services services;
	@Column(name = "title", nullable = false, length = 150)
	private String title;
	@Column(name = "descripttion", nullable = false, length = 500)
	private String descripttion;
	@Column(name = "price", nullable = false, precision = 53, scale = 0)
	private double price;
	@Temporal(TemporalType.DATE)
	@Column(name = "createdAt", length = 10)
	private Date createdAt;
	@Column(name = "timeToComplete", nullable = false, length = 50)
	private String timeToComplete;
	@Column(name = "sale", precision = 53, scale = 0)
	private double sale;
	@Column(name = "mainImage", nullable = true, length = 1000)
	private String mainImage;
	@Column(name = "content", nullable = false, length = 1000)
	private String content;
	@JsonIgnore
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "servicesDetails")
	private Set<ImageService> imageServiceses = new HashSet<ImageService>(0);

	public ServiceDetail() {

	}

	public ServiceDetail(Services services, String title, String descripttion, String content, double price,
			String timeToComplete, double sale, String mainImage) {
		super();
		this.services = services;
		this.title = title;
		this.descripttion = descripttion;
		this.price = price;
		this.timeToComplete = timeToComplete;
		this.sale = sale;
		this.mainImage = mainImage;
		this.content = content;
	}

	public ServiceDetail(Services services, String title, String descripttion, String content, double price,
			String timeToComplete, double sale) {
		super();
		this.services = services;
		this.title = title;
		this.descripttion = descripttion;
		this.price = price;
		this.timeToComplete = timeToComplete;
		this.sale = sale;
		this.mainImage = mainImage;
		this.content = content;
	}
	
	public ServiceDetail(int serviceDetailId, Services services, String title, String descripttion, String content,
			double price, String timeToComplete, double sale, String mainImage) {
		super();
		this.serviceDetailId = serviceDetailId;
		this.services = services;
		this.title = title;
		this.descripttion = descripttion;
		this.price = price;
		this.timeToComplete = timeToComplete;
		this.sale = sale;
		this.mainImage = mainImage;
		this.content = content;
	}

	public int getServiceDetailId() {
		return this.serviceDetailId;
	}

	public void setServiceDetailId(int serviceDetailId) {
		this.serviceDetailId = serviceDetailId;
	}

	public Services getServices() {
		return this.services;
	}

	public void setServices(Services services) {
		this.services = services;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getDescripttion() {
		return this.descripttion;
	}

	public void setDescripttion(String descripttion) {
		this.descripttion = descripttion;
	}

	public double getPrice() {
		return this.price;
	}

	public void setPrice(double price) {
		this.price = price;
	}

	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	public String getTimeToComplete() {
		return this.timeToComplete;
	}

	public void setTimeToComplete(String timeToComplete) {
		this.timeToComplete = timeToComplete;
	}

	public Double getSale() {
		return this.sale;
	}

	public void setSale(Double sale) {
		this.sale = sale;
	}

	public String getMainImage() {
		return this.mainImage;
	}

	public void setMainImage(String mainImage) {
		this.mainImage = mainImage;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public Set<ImageService> getImageServiceses() {
		return this.imageServiceses;
	}

	public void setImageServiceses(Set<ImageService> imageServiceses) {
		this.imageServiceses = imageServiceses;
	}

	@Override
	public String toString() {
		return title;
	}
	
	

}
